$(function () {
    'use strict';

    var siteName = 'Vtechiee';
    var siteUrl = 'https://visharaminfo.in/';
    var siteTitle = 'Vtechiee: Software Development, Website Design & Cloud Solutions';
    var siteDescription = 'Website development company in Melvisharam, Ranipet and Vellore offering React, PHP, Node, WordPress, eCommerce, SAP B1 support, hosting and cloud solutions.';

    document.title = siteTitle;
    $('meta[name="description"]').attr('content', siteDescription);
    $('meta[name="keywords"]').attr('content', 'website development, web design, software development, SAP B1 support, cloud solutions, hosting, ecommerce website, Melvisharam, Ranipet, Vellore');
    $('meta[name="author"]').attr('content', siteName);
    $('meta[property="og:title"]').attr('content', siteTitle);
    $('meta[property="og:site_name"]').attr('content', siteName);
    $('meta[property="og:url"]').attr('content', siteUrl);
    $('meta[property="og:description"]').attr('content', siteDescription);
    $('meta[name="twitter:title"]').attr('content', siteTitle);
    $('meta[name="twitter:description"]').attr('content', siteDescription);

    $('.header-title').filter(function () { return $.trim($(this).text()) === 'SAP B1 Support,Upgradtions'; }).text('SAP B1 Support & Upgrades');

    var $brandLogo = $('.navbar-brand-logo').first();
    if ($brandLogo.length && !$brandLogo.find('.brand-lockup').length) {
        $brandLogo.attr('aria-label', siteName);
        $brandLogo.html('<span class="brand-lockup"><span class="brand-mark">V</span><span class="brand-copy"><span class="brand-name">Vtechiee</span><span class="brand-tagline">IT Solutions</span></span></span>');
    }

    if (!$('.scroll-progress').length) $('body').prepend('<div class="scroll-progress"><span></span></div>');
    if (!$('.back-to-top').length) $('body').append('<button class="back-to-top" type="button" aria-label="Back to top">↑</button>');
    if (!$('.quick-contact-float').length) $('body').append('<a class="quick-contact-float" href="#contact" aria-label="Contact Vtechiee"><span>✉</span><strong>Contact</strong></a>');
    if (!$('.dev-pulse-layer').length) $('body').append('<div class="dev-pulse-layer" aria-hidden="true"><span></span><span></span><span></span><span></span></div>');

    if (!$('.trust-strip').length && $('.header').length) {
        $('.header').after('<section class="trust-strip" aria-label="Vtechiee highlights"><div class="trust-item"><strong>24/7</strong><span>Support</span></div><div class="trust-item"><strong>SAP B1</strong><span>Expertise</span></div><div class="trust-item"><strong>Cloud</strong><span>Solutions</span></div><div class="trust-item"><strong>Web</strong><span>Development</span></div></section>');
    }

    if (!$('.dev-console').length && $('.header-title-section').length) {
        $('.header-title-section').append('<div class="dev-console" aria-label="Live development status"><div class="dev-console-bar"><span></span><span></span><span></span><strong>live-build</strong></div><div class="dev-console-lines"><p><b>$</b> building responsive website...</p><p><b>✓</b> optimizing UI components</p><p><b>✓</b> deploying secure cloud-ready solution</p><p><b>→</b> status: <span class="typing-status">development in progress</span></p></div></div>');
    }

    if (!$('.floating-tech-stack').length && $('.header').length) {
        $('.header').append('<div class="floating-tech-stack" aria-hidden="true"><span>React</span><span>PHP</span><span>Node</span><span>SAP B1</span><span>Cloud</span><span>UI/UX</span></div>');
    }

    $('.service-box').each(function () {
        if (!$(this).find('.service-live-dot').length) $(this).prepend('<span class="service-live-dot"></span>');
    });

    var css = `
        :root{--vt-blue:#003379;--vt-dark:#061934;--vt-soft:#eef4ff;--vt-muted:#5f6f89;--vt-cyan:#1a75ff;--vt-green:#17b26a}
        html,body{max-width:100%;overflow-x:hidden;scroll-behavior:smooth}img,svg,video,canvas{max-width:100%;height:auto}a:focus,button:focus,input:focus,textarea:focus{outline:2px solid var(--vt-blue)!important;outline-offset:3px}.wrapper{overflow-x:hidden;overflow-y:visible}
        .scroll-progress{position:fixed;top:0;left:0;width:100%;height:4px;z-index:20000;background:rgba(0,51,121,.06)}.scroll-progress span{display:block;width:0;height:100%;background:linear-gradient(90deg,var(--vt-blue),var(--vt-cyan));box-shadow:0 0 14px rgba(0,51,121,.35);transition:width .08s linear}
        .navbar{z-index:1030;transition:padding .25s ease,box-shadow .25s ease,background-color .25s ease,transform .25s ease;backdrop-filter:saturate(130%) blur(10px)}.navbar-container,.navbar-collapse,.footer-container{max-width:100%}.navbar-brand{min-width:210px;margin-right:18px}.navbar-brand-logo,.navbar-brand-logo:hover,.navbar-brand-logo:focus{display:inline-flex;align-items:center;text-decoration:none}
        .brand-lockup{display:inline-flex;align-items:center;gap:12px;min-width:190px;padding:6px 0;transition:transform .25s ease}.brand-lockup:hover{transform:translateY(-1px)}.brand-mark{display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;border-radius:12px;background:var(--vt-blue);color:#fff;font-family:Inter,sans-serif;font-size:27px;font-weight:800;line-height:1;letter-spacing:-1px;box-shadow:0 8px 18px rgba(0,51,121,.18);animation:brandPulse 3.8s ease-in-out infinite}.brand-copy{display:flex;flex-direction:column;justify-content:center;line-height:1.05}.brand-name{color:var(--vt-blue);font-family:Inter,sans-serif;font-size:25px;font-weight:800;letter-spacing:-.8px;white-space:nowrap}.brand-tagline{margin-top:4px;color:var(--vt-muted);font-family:Inter,sans-serif;font-size:11px;font-weight:700;letter-spacing:1.4px;text-transform:uppercase;white-space:nowrap}.header-scrolled .brand-lockup{gap:10px}.header-scrolled .brand-mark{width:38px;height:38px;font-size:23px;border-radius:10px}.header-scrolled .brand-name{font-size:22px}.header-scrolled .brand-tagline{font-size:10px}
        .navbar-toggler{border:0;padding:8px 10px;transition:transform .2s ease}.navbar-toggler:hover{transform:scale(1.08)}.nav-link-menu{margin:0;position:relative}.nav-link-menu::after{content:'';position:absolute;left:50%;bottom:-8px;width:0;height:3px;border-radius:999px;background:var(--vt-blue);transform:translateX(-50%);transition:width .25s ease}.nav-link:hover .nav-link-menu::after,.nav-link.active .nav-link-menu::after{width:70%}.nav-link.active .nav-link-menu{color:var(--vt-blue)!important}
        .header{position:relative;overflow:hidden;isolation:isolate}.header::before{content:'';position:absolute;inset:-20% -10% auto auto;width:52%;height:72%;border-radius:999px;background:radial-gradient(circle,rgba(0,51,121,.10),transparent 68%);z-index:-1;animation:softBlob 12s ease-in-out infinite}.header::after{content:'';position:absolute;left:-8%;bottom:6%;width:30%;height:42%;border-radius:999px;background:radial-gradient(circle,rgba(26,117,255,.08),transparent 72%);z-index:-1;animation:softBlob 14s ease-in-out infinite reverse}.header-title{letter-spacing:-1px}.header-title,.about-title,.pricing-title h2,.vertical-slider-title,.testimonials-title{overflow-wrap:anywhere}
        .dev-pulse-layer{pointer-events:none;position:fixed;inset:0;z-index:0;overflow:hidden}.dev-pulse-layer span{position:absolute;width:6px;height:6px;border-radius:50%;background:rgba(0,51,121,.22);box-shadow:0 0 20px rgba(0,51,121,.28);animation:nodeDrift 12s linear infinite}.dev-pulse-layer span:nth-child(1){top:22%;left:8%}.dev-pulse-layer span:nth-child(2){top:46%;right:12%;animation-delay:-3s}.dev-pulse-layer span:nth-child(3){bottom:22%;left:20%;animation-delay:-6s}.dev-pulse-layer span:nth-child(4){bottom:14%;right:26%;animation-delay:-9s}
        .floating-tech-stack{position:absolute;inset:0;pointer-events:none;z-index:1}.floating-tech-stack span{position:absolute;padding:8px 12px;border-radius:999px;background:rgba(255,255,255,.86);border:1px solid rgba(0,51,121,.10);box-shadow:0 12px 28px rgba(0,0,0,.08);color:var(--vt-blue);font-size:12px;font-weight:800;animation:techFloat 7s ease-in-out infinite}.floating-tech-stack span:nth-child(1){top:18%;left:10%}.floating-tech-stack span:nth-child(2){top:26%;right:16%;animation-delay:-1s}.floating-tech-stack span:nth-child(3){bottom:20%;right:28%;animation-delay:-2s}.floating-tech-stack span:nth-child(4){bottom:16%;left:13%;animation-delay:-3s}.floating-tech-stack span:nth-child(5){top:52%;left:5%;animation-delay:-4s}.floating-tech-stack span:nth-child(6){top:58%;right:8%;animation-delay:-5s}
        .dev-console{margin-top:22px;max-width:470px;border-radius:18px;background:#061934;color:#dce8ff;box-shadow:0 24px 52px rgba(6,25,52,.22);overflow:hidden;text-align:left;animation:consoleIn 1.1s ease both}.dev-console-bar{display:flex;align-items:center;gap:7px;padding:10px 14px;background:rgba(255,255,255,.08)}.dev-console-bar span{width:10px;height:10px;border-radius:50%;background:#ff5f57}.dev-console-bar span:nth-child(2){background:#ffbd2e}.dev-console-bar span:nth-child(3){background:#28c840}.dev-console-bar strong{margin-left:8px;font-size:12px;letter-spacing:.8px;text-transform:uppercase;color:#b7c7e8}.dev-console-lines{padding:14px 16px}.dev-console-lines p{margin:0 0 7px;font-family:monospace;font-size:13px;font-weight:600;color:#dce8ff}.dev-console-lines p:last-child{margin-bottom:0}.dev-console-lines b{color:#4ad295}.typing-status{display:inline-block;border-right:2px solid #4ad295;white-space:nowrap;animation:cursorBlink .8s step-end infinite;color:#77e6ff}
        .learn-more-btn,.learn-extra-btn{text-align:center;white-space:normal;position:relative;overflow:hidden;transition:transform .25s ease,box-shadow .25s ease,background-color .25s ease}.learn-more-btn::before{content:'';position:absolute;top:0;left:-80%;width:55%;height:100%;background:linear-gradient(120deg,transparent,rgba(255,255,255,.34),transparent);transform:skewX(-20deg);transition:left .55s ease}.learn-more-btn:hover::before{left:130%}.learn-more-btn:hover,.learn-extra-btn:hover{transform:translateY(-3px);box-shadow:0 14px 28px rgba(0,51,121,.18)}
        .service-box,.blog-details,.pricing-card,.contact-form,.client-box{max-width:100%;transition:transform .28s ease,box-shadow .28s ease,background-color .28s ease}.service-box{position:relative;overflow:hidden}.service-box::after{content:'';position:absolute;inset:auto -30% -40% -30%;height:80px;background:radial-gradient(circle,rgba(0,51,121,.12),transparent 65%);opacity:0;transition:opacity .28s ease}.service-box:hover::after{opacity:1}.service-box:hover,.blog-details:hover,.pricing-card:hover,.contact-form:hover{transform:translateY(-8px);box-shadow:0 18px 38px rgba(0,0,0,.10)}.service-live-dot{position:absolute;right:18px;top:18px;width:10px;height:10px;border-radius:50%;background:var(--vt-green);box-shadow:0 0 0 0 rgba(23,178,106,.55);animation:liveDot 1.6s ease-out infinite}.client-box:hover{transform:translateY(-6px) scale(1.04);box-shadow:0 16px 32px rgba(0,0,0,.10)}.service-box .icon{transition:transform .28s ease}.service-box:hover .icon{transform:translateY(-4px) scale(1.08) rotate(-3deg)}
        .header-img-section img,.about-header-img img,.contact-header-img img{animation:floatVisual 6s ease-in-out infinite;will-change:transform}.header-title-section .header-title{animation:heroTitleIn .75s ease both}.header-title-section .header-title-text{animation:heroTextIn .9s ease both}.header-title-section .learn-more-btn-section{animation:heroButtonIn 1.05s ease both}.reveal-on-scroll{opacity:0;transform:translateY(34px);transition:opacity .72s ease,transform .72s ease;will-change:opacity,transform}.reveal-on-scroll.is-visible{opacity:1;transform:translateY(0)}.reveal-on-scroll.reveal-left{transform:translateX(-34px)}.reveal-on-scroll.reveal-right{transform:translateX(34px)}.reveal-on-scroll.reveal-left.is-visible,.reveal-on-scroll.reveal-right.is-visible{transform:translateX(0)}
        .contact-form .form-control{transition:border-color .2s ease,box-shadow .2s ease,transform .2s ease}.contact-form .form-control:focus{transform:translateY(-1px);box-shadow:0 10px 22px rgba(0,51,121,.10)}.trust-strip{max-width:1120px;margin:-32px auto 40px;padding:18px;display:grid;grid-template-columns:repeat(4,1fr);gap:14px;position:relative;z-index:4}.trust-item{background:rgba(255,255,255,.92);border:1px solid rgba(0,51,121,.08);border-radius:18px;padding:18px 16px;box-shadow:0 18px 40px rgba(0,0,0,.08);text-align:center;transition:transform .25s ease,box-shadow .25s ease}.trust-item:hover{transform:translateY(-6px);box-shadow:0 22px 44px rgba(0,51,121,.12)}.trust-item strong{display:block;color:var(--vt-blue);font-size:22px;font-weight:800;line-height:1.1}.trust-item span{display:block;margin-top:4px;color:var(--vt-muted);font-size:13px;font-weight:700;text-transform:uppercase;letter-spacing:.8px}
        .back-to-top{position:fixed;right:22px;bottom:92px;width:46px;height:46px;border:0;border-radius:50%;background:var(--vt-blue);color:#fff;font-size:22px;font-weight:800;z-index:1200;cursor:pointer;opacity:0;visibility:hidden;transform:translateY(12px);box-shadow:0 14px 30px rgba(0,51,121,.26);transition:opacity .25s ease,visibility .25s ease,transform .25s ease}.back-to-top.show{opacity:1;visibility:visible;transform:translateY(0)}.back-to-top:hover{transform:translateY(-4px)}.quick-contact-float{position:fixed;right:22px;bottom:28px;z-index:1200;display:inline-flex;align-items:center;gap:8px;padding:12px 16px;border-radius:999px;background:#fff;color:var(--vt-blue);border:1px solid rgba(0,51,121,.12);box-shadow:0 16px 34px rgba(0,0,0,.12);text-decoration:none;font-family:Inter,sans-serif;transition:transform .25s ease,box-shadow .25s ease}.quick-contact-float span{display:inline-flex;width:28px;height:28px;border-radius:50%;background:var(--vt-blue);color:#fff;align-items:center;justify-content:center}.quick-contact-float strong{font-size:14px}.quick-contact-float:hover{transform:translateY(-4px);color:var(--vt-blue);text-decoration:none;box-shadow:0 20px 42px rgba(0,51,121,.18)}
        @keyframes brandPulse{0%,100%{box-shadow:0 8px 18px rgba(0,51,121,.18)}50%{box-shadow:0 12px 28px rgba(0,51,121,.30)}}@keyframes floatVisual{0%,100%{transform:translateY(0)}50%{transform:translateY(-12px)}}@keyframes heroTitleIn{from{opacity:0;transform:translateY(22px)}to{opacity:1;transform:translateY(0)}}@keyframes heroTextIn{from{opacity:0;transform:translateY(26px)}to{opacity:1;transform:translateY(0)}}@keyframes heroButtonIn{from{opacity:0;transform:translateY(30px) scale(.97)}to{opacity:1;transform:translateY(0) scale(1)}}@keyframes softBlob{0%,100%{transform:translate3d(0,0,0) scale(1)}50%{transform:translate3d(-16px,18px,0) scale(1.08)}}@keyframes techFloat{0%,100%{transform:translateY(0) rotate(0)}50%{transform:translateY(-14px) rotate(2deg)}}@keyframes consoleIn{from{opacity:0;transform:translateY(18px) scale(.98)}to{opacity:1;transform:translateY(0) scale(1)}}@keyframes cursorBlink{50%{border-color:transparent}}@keyframes liveDot{to{box-shadow:0 0 0 13px rgba(23,178,106,0)}}@keyframes nodeDrift{0%{transform:translate3d(0,0,0) scale(1);opacity:.25}50%{transform:translate3d(30px,-45px,0) scale(1.4);opacity:.55}100%{transform:translate3d(0,0,0) scale(1);opacity:.25}}
        @media screen and (max-width:991px){.navbar{margin-top:0;padding-top:8px;padding-bottom:8px;background-color:#fff!important;box-shadow:0 4px 6px 0 rgba(12,0,46,.05)}.navbar-brand{min-width:auto;margin-right:0}.brand-lockup{min-width:auto;gap:10px;padding:4px 0}.brand-mark{width:40px;height:40px;font-size:24px;border-radius:11px}.brand-name{font-size:23px}.brand-tagline{font-size:10px;letter-spacing:1.1px}.navbar-collapse{width:100%;margin-top:10px;max-height:calc(100vh - 75px);overflow-y:auto;border-radius:0 0 12px 12px}.navbar-nav{align-items:stretch}.nav-item{margin-left:0;margin-right:0}.nav-item .nav-link{text-align:center;padding:10px 12px}.header{padding-top:115px;padding-bottom:55px;background-size:cover;background-position:center top}.header-container{padding-left:15px;padding-right:15px}.header-title-section{margin-top:24px;padding-left:0;padding-right:0}.header-title{font-size:34px;line-height:1.2}.header-title-text{font-size:16px;line-height:1.5}.about-title,.pricing-title h2,.vertical-slider-title{font-size:32px;line-height:1.25}.footer-subsection,.footer-logo{padding-left:15px;padding-right:15px}.trust-strip{grid-template-columns:repeat(2,1fr);margin:10px 15px 30px}.dev-console{margin-left:auto;margin-right:auto}.floating-tech-stack{display:none}}
        @media screen and (max-width:575px){.navbar{min-height:76px}.brand-lockup{gap:8px}.brand-mark{width:38px;height:38px;font-size:23px;border-radius:10px}.brand-name{font-size:21px}.brand-tagline{font-size:9px;letter-spacing:.9px}.ti-layout-grid2{font-size:28px}.header{padding-top:105px;padding-bottom:45px}.header-title{font-size:28px!important;line-height:1.2;margin-bottom:12px}.header-title-text{font-size:15px!important;line-height:1.55;margin-bottom:18px}.learn-more-btn-section{justify-content:center;width:100%}.learn-more-btn,.learn-extra-btn{width:100%;max-width:290px;font-size:14px!important;padding:10px 14px!important;margin-left:auto;margin-right:auto}.about-title,.pricing-title h2,.vertical-slider-title{font-size:28px}.about-text,.vertical-slider-text,.testimonials-slider-text,.footer-logo p,.footer-subsection-text,.footer-subsection-list li{font-size:15px;line-height:1.55}.service-list .service-box{padding:22px}.client-box{width:120px;height:120px}form.contact-form{padding:16px}.trust-strip{grid-template-columns:1fr 1fr;gap:10px;padding:10px}.trust-item{padding:14px 10px;border-radius:14px}.trust-item strong{font-size:18px}.trust-item span{font-size:11px}.quick-contact-float{right:14px;bottom:20px;padding:10px 12px}.quick-contact-float strong{display:none}.back-to-top{right:14px;bottom:78px;width:42px;height:42px}.dev-console{display:none}}
        @media screen and (max-width:360px){.brand-mark{width:34px;height:34px;font-size:20px}.brand-name{font-size:19px}.brand-tagline{display:none}.header-title{font-size:25px!important}}@media (prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.01ms!important}.reveal-on-scroll{opacity:1!important;transform:none!important}.dev-pulse-layer,.floating-tech-stack{display:none!important}}
    `;

    $('#mobile-responsive-hotfix').remove();
    $('<style id="mobile-responsive-hotfix"></style>').text(css).appendTo('head');

    var revealSelectors = ['.trust-item','.dev-console','.about-title-section','.about-header-img','.services-section .col-lg-4','.blog-section .col-lg-12','.client-box','.contact-section .col-lg-6','.contact-section .col-lg-5','.footer-section .col-lg-4','.footer-section .col-lg-3','.footer-section .col-lg-2','.footer-credits'].join(',');
    $(revealSelectors).each(function(index){var $item=$(this);$item.addClass('reveal-on-scroll');if(index%3===1)$item.addClass('reveal-left');if(index%3===2)$item.addClass('reveal-right');$item.css('transition-delay',Math.min(index*45,240)+'ms')});
    if('IntersectionObserver'in window){var revealObserver=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}})},{threshold:.12,rootMargin:'0px 0px -40px 0px'});document.querySelectorAll('.reveal-on-scroll').forEach(function(el){revealObserver.observe(el)})}else{$('.reveal-on-scroll').addClass('is-visible')}

    function updateScrollUi(){var scrollTop=$(window).scrollTop();var docHeight=Math.max($(document).height()-$(window).height(),1);$('.scroll-progress span').css('width',Math.min(100,(scrollTop/docHeight)*100)+'%');$('.back-to-top').toggleClass('show',scrollTop>500);var current='';$('div[id], section[id]').each(function(){if($(this).offset().top-120<=scrollTop)current=this.id});if(current){$('.navbar-nav .nav-link').removeClass('active');$('.navbar-nav .nav-link[href="#'+current+'"]').addClass('active')}}
    $(window).on('scroll resize',updateScrollUi);updateScrollUi();$('.back-to-top').on('click',function(){$('html, body').animate({scrollTop:0},550)});

    var statusWords=['development in progress','UI polishing live','cloud build running','security check passed','responsive mode active'];var statusIndex=0;setInterval(function(){statusIndex=(statusIndex+1)%statusWords.length;$('.typing-status').fadeOut(180,function(){$(this).text(statusWords[statusIndex]).fadeIn(180)})},2400);

    jQuery('#preloader').delay(500).fadeOut(500);$(window).scroll(function(){if($(this).scrollTop()>20)$('#navbar').addClass('header-scrolled');else $('#navbar').removeClass('header-scrolled')});if($.fn.owlCarousel)$('.owl-testimonials-slider').owlCarousel({items:1,loop:true,nav:true,autoplay:true,autoplayTimeout:5000,autoplayHoverPause:false,responsiveClass:true,responsive:{0:{items:1},600:{items:1},1000:{items:1}}});$('.navbar-mobile .nav-item .nav-link').on('click',function(){var $navbarCollapse=$('#navbarNav');if($(window).width()<=991&&$navbarCollapse.hasClass('show'))$('.navbar-toggler').trigger('click')});$(window).on('resize',function(){if($(window).width()>991){$('#navbarNav').removeClass('show');$('.navbar-toggler').attr('aria-expanded','false')}});

    var $contactForm=$('.contact-form').first();if($contactForm.length){var cleanForm=$contactForm.clone(false)[0];$contactForm[0].parentNode.replaceChild(cleanForm,$contactForm[0]);$contactForm=$(cleanForm);$contactForm.on('submit',function(event){event.preventDefault();var name=$.trim($('#name').val()||''),mobile=$.trim($('#mobile').val()||''),email=$.trim($('#email').val()||''),message=$.trim($('#message').val()||'');var emailPattern=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;var mobilePattern=/^[0-9+\-\s()]{7,20}$/;if(!name||!mobile||!email||!message)return alert('Please fill in all required details.');if(!emailPattern.test(email))return alert('Please enter a valid email address.');if(!mobilePattern.test(mobile))return alert('Please enter a valid mobile number.');var $submitButton=$contactForm.find('button[type="submit"], input[type="submit"]').first();var originalButtonText=$submitButton.is('input')?$submitButton.val():$submitButton.text();function setButton(text,disabled){if($submitButton.length){$submitButton.prop('disabled',disabled);$submitButton.is('input')?$submitButton.val(text):$submitButton.text(text)}}function resetButton(){setButton(originalButtonText,false)}setButton('Sending...',true);if(window.emailjs&&typeof emailjs.sendForm==='function')emailjs.sendForm('service_6iixv9p','template_pkr57uq',cleanForm).then(function(){alert('Message sent successfully!');cleanForm.reset();resetButton()},function(error){console.log(error);alert('Failed to send message. Please try again.');resetButton()});else $.ajax({type:'POST',url:'https://visharaminfo.in/contact.php',data:{name:name,email:email,mobile:mobile,message:message},success:function(resultData){alert(resultData||'Message sent successfully!');cleanForm.reset();resetButton()},error:function(err){console.log(err);alert('Failed to send message. Please try again.');resetButton()}})})}
});
