$(function () {
    'use strict';
    document.title = 'Vtechiee: SMB Websites, Business Portals, Cloud Care & SAP B1 Support';
    $('meta[name="description"]').attr('content', 'Vtechiee helps SMBs launch revenue-ready websites, e-commerce stores, business portals, managed cloud support and SAP Business One support.');
    $('meta[property="og:url"]').attr('content', 'https://vtechiee.com/');
    $('meta[property="og:image"]').attr('content', 'https://vtechiee.com/images/vtechiee-logo.svg');
    $('meta[name="twitter:image"]').attr('content', 'https://vtechiee.com/images/vtechiee-logo.svg');
    $('link[rel="icon"]').attr('href', 'images/vtechiee-favicon.svg?v=3').attr('type', 'image/svg+xml');
    if (!$('link[href="css/growth-base.css"]').length) $('head').append('<link rel="stylesheet" href="css/growth-base.css">');
    if (!$('script[src="js/growth-layer.js"]').length) $.getScript('js/growth-layer.js');
    $('.header-title').filter(function () { return $.trim($(this).text()) === 'SAP B1 Support,Upgradtions'; }).text('SAP B1 Support & Upgrades');
    var $brandLogo = $('.navbar-brand-logo').first();
    if ($brandLogo.length) $brandLogo.attr('aria-label','Vtechiee').html('<img src="images/vtechiee-logo.svg?v=3" class="vtechiee-main-logo" alt="Vtechiee Cloud SAP Software">');
    $('#vtechiee-logo-style').remove();
    $('<style id="vtechiee-logo-style"></style>').text('.navbar-brand{min-width:260px!important;display:flex!important;align-items:center!important}.navbar-brand-logo{display:flex!important;align-items:center!important}.navbar-brand-logo img.vtechiee-main-logo,.navbar .navbar-brand img.vtechiee-main-logo,.header-scrolled .navbar-brand img.vtechiee-main-logo{width:245px!important;max-width:245px!important;height:auto!important;margin-left:0!important;display:block!important}.navbar{min-height:78px!important;padding-top:8px!important;padding-bottom:8px!important}.header-scrolled{height:78px!important;min-height:78px!important}.header-scrolled .navbar-brand img.vtechiee-main-logo{width:225px!important;max-width:225px!important}@media(max-width:1200px){.navbar-brand{min-width:230px!important}.navbar-brand-logo img.vtechiee-main-logo,.navbar .navbar-brand img.vtechiee-main-logo,.header-scrolled .navbar-brand img.vtechiee-main-logo{width:220px!important;max-width:220px!important}}@media(max-width:991px){.navbar-brand{min-width:auto!important}.navbar-brand-logo img.vtechiee-main-logo,.navbar .navbar-brand img.vtechiee-main-logo,.header-scrolled .navbar-brand img.vtechiee-main-logo{width:205px!important;max-width:205px!important}.navbar,.header-scrolled{min-height:74px!important;height:auto!important}}@media(max-width:575px){.navbar-brand-logo img.vtechiee-main-logo,.navbar .navbar-brand img.vtechiee-main-logo,.header-scrolled .navbar-brand img.vtechiee-main-logo{width:175px!important;max-width:175px!important}.navbar,.header-scrolled{min-height:70px!important}}').appendTo('head');
    if ($.fn.owlCarousel) $('.owl-testimonials-slider').owlCarousel({items:1,loop:true,nav:true,autoplay:true,autoplayTimeout:5000,autoplayHoverPause:false});
    $('.navbar-mobile .nav-item .nav-link').on('click',function(){var $nav=$('#navbarNav');if($(window).width()<=991&&$nav.hasClass('show'))$('.navbar-toggler').trigger('click');});
    $(window).on('scroll',function(){if($(this).scrollTop()>20)$('#navbar').addClass('header-scrolled');else $('#navbar').removeClass('header-scrolled');});
    jQuery('#preloader').delay(500).fadeOut(500);
});
